Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import ArticleListview, ModelNameDetail

app_name = 'Blog'

urlpatterns = [

    path('',ArticleListview.as_view(),name="list_view"),


]

app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

from .views import (
    add_to_cart,
    home_view,
    contact_view,
    about_view,
    letters,
    HomeView,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    success,
    failure,
    cancel,
    error404,
    viewpdf,
    organizations_trained,
    pilot_list,
    gallery,
    testimonial,
    course_detail,
    IIDLocations,
    TrainingSchedule,
    franchise,
    webinar,
    databaserror,
  CheckoutView_subscription,
    Domptest,
    successsubcription

)

app_name = 'app'

urlpatterns = [

    # URLs for navbar and homepage
    path('', home_view, name="home"),
    path('courses_list/', HomeView.as_view(), name='courses'),
    path('about/', about_view, name="about"),
    path('gallery/', gallery, name="gallery"),
    path('instructors/', TemplateView.as_view(template_name='app/instructors.html'), name="instructors"),
    path('FAQs/', TemplateView.as_view(template_name='app/faqs.html'), name="FAQs"),
    path('DGCA/', TemplateView.as_view(template_name='app/dgca.html'), name="DGCA"),
    path('certification/', TemplateView.as_view(template_name='app/certification.html'), name="certification"),
    path('pilot-list/', pilot_list, name="pilot-list"),
    path('drone-jobs/', TemplateView.as_view(template_name='app/about_us.html'), name="drone-jobs"),
    path('testimonials/', testimonial, name="testimonials"),
    path('news-and-media/', TemplateView.as_view(template_name='app/news-events.html'), name="news-and-events"),
    path('infrastructure/', TemplateView.as_view(template_name='app/infrastructure.html'), name="infrastructure"),
    path('organizations-trained/', organizations_trained, name="organizations"),
    path('contact/', contact_view, name="contact"),
    path('satisfactory-letters/', letters, name="letters"),
    path('error/', error404, name="error"),
    path('terms-and-conditions/', TemplateView.as_view(template_name='app/terms-conditions.html'), name="t-c"),
    path('indemnity/', TemplateView.as_view(template_name='app/indemnity.html'), name="indemnity"),
    path('privacy/', TemplateView.as_view(template_name='app/privacy.html'), name="privacy"),
    path('cookies/', TemplateView.as_view(template_name='app/cookies.html'), name="cookies"),
    #path('franchise/', TemplateView.as_view(template_name='app/franchise.html'), name="franchise"),
    path('franchise/', franchise, name="franchise"),
    
    # URLs for Courses, Cart, Payment and pdf
    path('course/<slug>/', course_detail, name='course-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('success/', success, name='order.success'),
    path('failure/', failure, name='order.failure'),
    path('cancel/', cancel, name='order.cancel'),

    path('pdf_view/<slug:tid>', viewpdf, name="pdf_view"),

    path('pdf_template/', TemplateView.as_view(template_name='app/invoice.html')),

    path('iid-locations',IIDLocations.as_view(),name="iid-loc"),
    path('training-schedule',TrainingSchedule.as_view(),name="tr-schedule"),
    path('webinar-events',webinar, name="webinar"),
    path("databaserror",databaserror,name="databaserror"),

    path("CheckoutView_subscription/<str:pk>/",CheckoutView_subscription.as_view(),name="CheckoutView_subscription"),
    path('certificationform',Domptest,name="Domptest"),
    path('subscription/order',successsubcription,name="order.success1")
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_view, logout_view
from django.contrib.auth import views as auth_views  # for pass change and reset views
from django.conf import settings  # for profile pic
from django.conf.urls.static import static  # for profile pic

from django.views.defaults import page_not_found, permission_denied, bad_request, server_error
from django.http import Http404
from django.views.generic.base import RedirectView
from django.views.csrf import csrf_failure
from Blog.views  import ModelNameDetail


urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('ss',include('jobsportal.urls',namespace='jobportal')),
    path('store/', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    # path('', include('django.contrib.auth.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('captcha/', include('captcha.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('404/', page_not_found, {'exception': Http404()}),
    path('403/', permission_denied, {'exception': Http404()}),
    path('500/', server_error),
    path('400/', bad_request, {'exception': Http404()}),
    path('blog/',include('Blog.urls',namespace='Blog')),
    path('<slug:slug>/',ModelNameDetail.as_view(),name="model_detail"),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Blog/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from django.urls import reverse

class Author(models.Model):
    name=models.CharField(max_length=50)
    Img=models.ImageField(upload_to="Blog/AuthorImage/")

    def __str__(self):
        return self.name

class Article(models.Model):
    author=models.ForeignKey(Author,on_delete=models.CASCADE,default=None)
    title=models.CharField(max_length=60)
    slug=models.SlugField(null=True)
    Description=models.CharField(null=True,max_length=100)
    Date=models.DateField(blank=True)
    Content=RichTextField(blank=True,default="Main Blog Content",null=True)    
    CoverImage=models.ImageField(blank=True,upload_to="Blog/CoverImage/")  

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("model_detail" , kwargs={"slug": self.slug})

    
    @property
    def imageurl(self):
        try:
            url=self.CoverImage.url
        except:
            url=''

        return url    

    def show(self):
        return self.author

    def image(self):
        return self.author.Img.url
    

Blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import *


class ArticleListview(ListView):
    queryset=Article.objects.order_by('-id')
    model=Article
    template_name="Blog.html"
    paginate_by = 6

#after slugify 
class ModelNameDetail(DetailView):
    model = Article
    template_name="Blogslug.html"

Blog/templates/Blog.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_head %}
<title>Blog - Indian Institute of Drones | Military Certified Drone Pilot Instructors</title>
<meta name="keywords" content="drone pilot courses, online drone courses, fixed wing drone pilot training, multirotor drone pilot training">
<meta name="description" content="">

<style>
    :root{
        --transition-time: 0.5s;
    }
    .blog-header{
        background-image: linear-gradient(rgba(40, 59, 98, 0.6), rgba(40, 59, 98, 0.6)), url("/static/images/univ-header.jpg");
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }
    .blog-header h1{
        color: #fff;
        margin: 80px 0px;
        font-size: 3rem;   
    }
    .cards-wrapper{
        display: grid;
        justify-content: center;
        align-content: center;
        border-radius: 1em;
        background-size: cover;
        background-position: center;
        box-shadow: 0 0 3em -1em black;
        transition: all, var(--transition-time);
        border: 10px solid #ccc;
    }
    .cards-wrapper:hover{
        transform: scale(0.95)
    }
    .card-content{
        padding: 4rem 0.5rem 0.5rem;
    }
    .white-hr{
        border-color: #fff;
        margin-bottom: 0;
    }
    .black-hr{
        border-color: #000;
        margin-top: 0;
    }
    .blog-card{
        padding: 1rem 1rem;
        height: 25em;
        color: #fff;
        border-radius: 0.3rem;
        display: flex;
        align-items: flex-end;
        position: relative;
        overflow: hidden;
        text-decoration: none;
        transition: all, var(--transition-time);
    }
    .blog-card:hover{
        text-decoration: none;
        transform: rotate(0);
        color: var(--color);
        background: var(--color);
        color: #000;
    }
    .blog-card h1{
        margin: 0;
        font-size: 1.8em;
        line-height: 1.2em;
    }
    .blog-desc{
        font-size: 0.85em;
        margin-top: 1em;
        line-height: 1.8em;
    }
    .blog-card:before, .blog-card:after {
        content: '';
        transform: scale(0);
        transform-origin: top left;
        border-radius: 50%;
        position: absolute;
        left: -50%;
        top: -50%;
        z-index: -5;
        transition: all, var(--transition-time);
        transition-timing-function: ease-in-out;
    }
    .blog-card:hover:before, .blog-card:hover:after {
        transform: scale(1);
    }
    .blog-card:before {
        background: #ddd;
        width: 250%;
        height: 250%;
    }
    .blog-card:after {
        background: white;
        width: 250%;
        height: 250%;
    }
    .blog-card .date{
        position: absolute;
        top: 1em;
        right: 2em;
        padding: 2px;
        font-size: 1.2em;
    }
    .blog-author-img{
        display: inline-block;
        padding: 0px !important;
        height: 50px;
        width: 50px;
        border-radius: 50% 50%;
        margin-right: 10px;
    }
    .blog-author-name{
        font-size: 1.5em;
        font-weight: 500;
        margin: 0;
        display: inline-block;
        opacity: 0.9;
    }
    @media only screen and (max-device-width: 480px) {
        .blog-card{
        height: 28em;
        }
        .blog-card h1{
        font-size: 1.5em;
        line-height: 1.1em;
    }
    }
</style>

{% endblock %}

{% block content %}
<div class="container-fluid blog-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>BLOG</h1>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="container">
        <div class="row py-4">
            {% for article in object_list %}
            <div class="col-sm-6">
                <div class="cards-wrapper" style="background-image: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.5)), url({{article.imageurl}});">
                    <div class="card-grid-space">
                        <a class="blog-card" href="{{ article.get_absolute_url }}">
                            <div class="card-content">
                                <h1>{{article.title}}</h1>
                                <p class="blog-desc">{{article.Description}}..</p>
                                <div class="date">{{article.Date}}</div>
                                <hr class="white-hr">
                                <hr class="black-hr">
                                <img class="blog-author-img" src="{{article.author.Img.url}}">
                                <p class="blog-author-name">{{article.author}}</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
        <div class="row py-3">
            <div class="col-sm-12">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
                    {% endif %}

                    {% if page_obj.number|add:'-4' > 1 %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>

                    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Blog/templates/Blogslug.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_head %}
<title>Blog - Indian Institute of Drones | Military Certified Drone Pilot Instructors</title>
<meta name="keywords" content="drone pilot courses, online drone courses, fixed wing drone pilot training, multirotor drone pilot training">
<meta name="description" content="">

<style>
    .blog-content{
        margin-left: auto;
        margin-right: auto;
        margin-top: 10px;
        margin-bottom: 10px;
        background-color: #fff;
        padding: 20px !important;
        border: solid 0.1px #adadad;
    }
    .auth-img{
        border-radius: 50% 50%;
        width: 60px;
        display: inline-block;
    }
    .auth-details{
        padding-left: 10px;
        display: inline-block;
        vertical-align: middle;
    }
    .auth-name{
        font-size: 110%;
        line-height: 0.5;
    }
    .blog-date,
    .reading-time{
        font-size: 80%;
        opacity: 0.9;
        line-height: 0.5;
    }
    .share-link {
        float: right;
        border: none;
        background-color: #fff !important;
    }
    .blog-img{
        padding-top: 20px;
        padding-bottom: 10px;
    }
    .blog-title{
        margin: 0;
        padding: 20px 0px;
        font-size: 200%;
    }
    .return:hover{
        text-decoration: none;
    }
    .blog-cover-img{
        margin-top: 20px;
        background-image: url({{object.imageurl}});
        min-height: 400px;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
    }
    @media only screen and (max-device-width: 480px){
        .blog-cover-img{
            min-height: 300px;
        }
    }
</style>

{% endblock %}

{% block content %}

<div class="container-fluid" style="background-color: #eaeaea;">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 blog-content">
                <div class="row">
                    <div class="col-sm-8">
                        <img class="auth-img" src="{{object.image}}" alt="{{object.show}}">
                        <span class="auth-details">
                            <span class="auth-name">{{object.show}}</span><br>
                            <span class="blog-date">{{object.Date}}</span> | <span class="reading-time"></span>
                        </span>
                    </div>
                </div>
                
<!--
                <button class="share-link" onclick="copyURL()">
                    <span></span><i class="fas fa-link"></i>
                </button>
-->
                <div class="blog-cover-img"></div>
                <article id="post">    
                    <h1 class="blog-title">{{object.title}}</h1>
                    <p>{{object.Content | safe}}</p>
                    {{object.datetrue}}
                </article>
                <hr>
                <a class="return" href="{% url 'Blog:list_view' %}"><i class="fas fa-angle-left"></i> Back to Blogs</a>
            </div>
        </div>
    </div>
</div>

<script>    
    const post = document.getElementById("post");
    const readingTimeSummary = document.querySelector(".reading-time");
    const avgWordsPerMin = 250;

    setReadingTime();

    function setReadingTime() {
      let count = getWordCount();
      let time = Math.ceil(count / avgWordsPerMin);

      readingTimeSummary.innerText = time + " min. read";
    }

    function getWordCount() {
      return post.innerText.match(/\w+/g).length;
    }

</script>



{% endblock %}