app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

from .views import (
    add_to_cart,
    home_view,
    contact_view,
    about_view,
    letters,
    HomeView,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    success,
    failure,
    cancel,
    error404,
    viewpdf,
    organizations_trained,
    pilot_list,
    gallery,
    testimonial,
    course_detail,
    IIDLocations,
    TrainingSchedule,
    franchise,
    webinar,
    databaserror,
  CheckoutView_subscription,
    Domptest,
    successsubcription

)

app_name = 'app'

urlpatterns = [

    # URLs for navbar and homepage
    path('', home_view, name="home"),
    path('courses_list/', HomeView.as_view(), name='courses'),
    path('about/', about_view, name="about"),
    path('gallery/', gallery, name="gallery"),
    path('instructors/', TemplateView.as_view(template_name='app/instructors.html'), name="instructors"),
    path('FAQs/', TemplateView.as_view(template_name='app/faqs.html'), name="FAQs"),
    path('DGCA/', TemplateView.as_view(template_name='app/dgca.html'), name="DGCA"),
    path('certification/', TemplateView.as_view(template_name='app/certification.html'), name="certification"),
    path('pilot-list/', pilot_list, name="pilot-list"),
    path('drone-jobs/', TemplateView.as_view(template_name='app/about_us.html'), name="drone-jobs"),
    path('testimonials/', testimonial, name="testimonials"),
    path('news-and-media/', TemplateView.as_view(template_name='app/news-events.html'), name="news-and-events"),
    path('infrastructure/', TemplateView.as_view(template_name='app/infrastructure.html'), name="infrastructure"),
    path('organizations-trained/', organizations_trained, name="organizations"),
    path('contact/', contact_view, name="contact"),
    path('satisfactory-letters/', letters, name="letters"),
    path('error/', error404, name="error"),
    path('terms-and-conditions/', TemplateView.as_view(template_name='app/terms-conditions.html'), name="t-c"),
    path('indemnity/', TemplateView.as_view(template_name='app/indemnity.html'), name="indemnity"),
    path('privacy/', TemplateView.as_view(template_name='app/privacy.html'), name="privacy"),
    path('cookies/', TemplateView.as_view(template_name='app/cookies.html'), name="cookies"),
    #path('franchise/', TemplateView.as_view(template_name='app/franchise.html'), name="franchise"),
    path('franchise/', franchise, name="franchise"),
    
    # URLs for Courses, Cart, Payment and pdf
    path('course/<slug>/', course_detail, name='course-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('success/', success, name='order.success'),
    path('failure/', failure, name='order.failure'),
    path('cancel/', cancel, name='order.cancel'),

    path('pdf_view/<slug:tid>', viewpdf, name="pdf_view"),

    path('pdf_template/', TemplateView.as_view(template_name='app/invoice.html')),

    path('iid-locations',IIDLocations.as_view(),name="iid-loc"),
    path('training-schedule',TrainingSchedule.as_view(),name="tr-schedule"),
    path('webinar-events',webinar, name="webinar"),
    path("databaserror",databaserror,name="databaserror"),

    path("CheckoutView_subscription/<str:pk>/",CheckoutView_subscription.as_view(),name="CheckoutView_subscription"),
    path('certificationform',Domptest,name="Domptest"),
    path('subscription/order',successsubcription,name="order.success1")
    
]

jobsportal/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.views.generic import TemplateView
app_name = 'jobportal'


urlpatterns = [
   

  path('post/<slug>',Post1,name="Post1"),
  path('createstudent',createstudent,name="createstudent"),
  path('create',check_current_account,name="checkcurrent"),
  path('allcategory',allcategory_all,name="allcategory"),
  path('modeldetail1/<pk>',modeldetail1category,name="modeldetail1"),
  path('updateprofile',updateprofile,name="updateprofile"),
  path('temp', TemplateView.as_view(template_name="notify.html"),name="notify"),
  path('',filter,name="filter"),
  path('student_apply1/<pk>',student_apply1,name="student_apply1")

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_view, logout_view
from django.contrib.auth import views as auth_views  # for pass change and reset views
from django.conf import settings  # for profile pic
from django.conf.urls.static import static  # for profile pic

from django.views.defaults import page_not_found, permission_denied, bad_request, server_error
from django.http import Http404
from django.views.generic.base import RedirectView
from django.views.csrf import csrf_failure
from Blog.views  import ModelNameDetail


urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('ss',include('jobsportal.urls',namespace='jobportal')),
    path('store/', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    # path('', include('django.contrib.auth.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('captcha/', include('captcha.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('404/', page_not_found, {'exception': Http404()}),
    path('403/', permission_denied, {'exception': Http404()}),
    path('500/', server_error),
    path('400/', bad_request, {'exception': Http404()}),
    path('blog/',include('Blog.urls',namespace='Blog')),
    path('<slug:slug>/',ModelNameDetail.as_view(),name="model_detail"),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobsportal/views.py
from django import http
from django.http.response import Http404, HttpResponseBadRequest
from django.shortcuts import render
from django.http import HttpResponse, request
from django.template.defaultfilters import title
from django.views import View
from .models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib import messages

def jobportalhome(request):  
    
    if request.method == "POST":
     
        s1=request.POST.get('id3')
        s2=request.POST.get('id3')

        jobs=Job.objects.filter(title=s1)
        print(jobs)

        job1=True
        context={'s3':s1,"job":jobs,'Job1':job1}

        print(s1)

        return render(request,"homejobs.html",context)        
    return render(request,'homejobs.html',{'job':False})


class GreetingView(View):
    
    def get(self, request):
        return HttpResponse(self.greeting)

    def post(self,request):
        return HttpResponse("this is working on day")

def search_box(request):
    
    return render(request,"request.html")


@login_required(login_url='/login/')
def Post1(request,slug):    

    specificjobs=Job.objects.filter(slug=slug)[0]
    member_specific=UserMembership.objects.filter(jobs_add=specificjobs).first()

    if request.method=='POST':
        try:
            student=student_apply.objects.filter(student_profile__email=request.user)[0]
          
            if student:
                ss=Application.objects.create(profilename=str(request.user),students=student,job=specificjobs)
                ss.save()
                # add error
                if member_specific.Application_apply.all().filter(profilename=ss.profilename).exists():
                    messages.success(request, 'already apply for this job')
                    return redirect("jobportal:jobportalhome")

                else:
                    member_specific.Application_apply.add(ss)
                    member_specific.save()
        
                
                messages.success(request, 'successfully  apply for this job')
                return redirect("jobportal:jobportalhome") 


            else:
                return redirect("jobportal:jobportalhome") 
        except:
            return redirect("jobportal:createstudent")    
        
        
        return render(request,"homejobs.html")
    
    return render(request,"specificjobs.html",{"jobsdesc":specificjobs ,"jobs":member_specific})



from .form import studentaplyforms

def createstudent(request):
    pass


def check_current_account(request):
    ss=UserMembership.objects.filter(UserMembership__email=request.user)[0]
    HttpResponse("this is my response",ss)


def allcategory_all(request):
    allentry=allcategory.objects.all()

    return render(request,"student_application.html",{'allentry':allentry})


def modeldetail1category(request,pk):
    student=student_apply.objects.filter(student_profile__email=request.user).first()
    print(student)
    s1=Account.objects.get(email=request.user)
    
    if student:
        if pk=="todo":
            messages.info(request,' update your account')
        else:
            messages.info(request,'you cannnot apply please update your account')
        return render(request,"application.html",{"s1":s1,"student":student})
    else:
        studentform=studentaplyforms()
        if request.method=="POST":
            form = studentaplyforms(request.POST, request.FILES)
            if form.is_valid():
                Experience=form.cleaned_data['Experience']
                resume=form.cleaned_data['resume']
                Category=form.cleaned_data['Category']
                Zone=form.cleaned_data['zone']
                s1=Account.objects.get(email=request.user)
                studentformssave=student_apply.objects.create(student_profile=s1,Experience=Experience,resume=resume,Category=Category,zone=Zone)
                studentformssave.save()
            else:
                return Http404("error 404")
        return render(request,"studentinfo.html",{'student':studentform}) 

def updateprofile(request):
    studentform=studentaplyforms()
    if request.method=="POST":
        form = studentaplyforms(request.POST, request.FILES)
        if form.is_valid():
            Experience=form.cleaned_data['Experience']
            resume=form.cleaned_data['resume']
            Category=form.cleaned_data['Category']
            Zone=form.cleaned_data['zone']
            s1=Account.objects.get(email=request.user)
            studentformssave=student_apply.objects.get(student_profile=s1)
            studentformssave.Experience=Experience
            studentformssave.resume=resume
            studentformssave.Category=Category
            studentformssave.Zone=Zone 
            studentformssave.save()
            return redirect("jobportal:modeldetail1", pk='todo')
        else:
            return Http404("error 404")
    return render(request,"studentupdate.html",{'student':studentform}) 


def filter(request):
    user=UserMembership.objects.filter(usermembership__email=request.user).first()
    print(user)

    if user and  not (str(user.membership_method) == str('Free')):
        students=student_apply.objects.all()


    else:
        students=False
        return redirect("account:subscription")
        # return HttpResponseBadRequest("Bad request")

    return render(request,"filter.html",{'student_apply':students})

def student_apply1(request,pk):
    students=student_apply.objects.get(pk=pk)
    print(students)
    context={'students':students}
    return render(request,"studentdetail.html",context)

jobsportal/templates/application.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}

{% load crispy_forms_tags %}
<title>My Account - Indian Institute of Drones</title>

<style>
    .profile-image{
    vertical-align: middle;
    width: 270px;
    height: auto;
    border-radius: 5px;
}
</style>
{% endblock %}
{% block content %}



<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>MY ACCOUNT</h1>
            </div>
        </div>
    </div>
</div>

<section class="my-profile py-4">
  <div class="container-fluid">
		<div class="container">
			<div class="row">
        <div class="col-sm-1"></div>
				<div class="col-md-5 col-sm-12">
					<center>
            <img src="{{request.user.pro_pic.url}}" class="profile-image">
            <br><br>
            <p style="font-size: 120%; font-weight: 500">
              {{ request.user.first_name }} {{ request.user.last_name }}
              <br>{{ request.user.email }}
              <br>{{ request.user.phone }}          
            </p>
          </center>
          <br>    
           {% comment %} <a href="{% url ''%}"><button class="btn btn-block btn-md btn-primary">update profile</button></a>  {% endcomment %}
          <br>
      
        
        <a href="{% url 'jobportal:updateprofile' %}"><button type="submit" class="btn btn-block btn-md btn-primary mb-4">update Current profile</button> </a> 
                      
				</div>
    
				<div class="col-md-5 col-sm-12">
          
          {% if t%}
          {% else %}
          <form>
            <fieldset disabled>
              <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <input type="text" id="disabledTextInput" class="form-control" placeholder="{{student.Category}}">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Experience</label>
                <input type="text" id="disabledTextInput" class="form-control" placeholder="{{student.Experience}} year">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Student Zone</label>
                <input type="text" id="disabledTextInput" class="form-control" placeholder="{{student.zone}}">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Resume</label>
                <input type="text" id="disabledTextInput" class="form-control" placeholder="{{student.resume}}">
              </div>
            
          </fieldset>
          </form>

          {% endif %}


				

</section>
{% endblock %}

jobsportal/templates/filter.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}

{% load crispy_forms_tags %}
<title>My Account - Indian Institute of Drones</title>

<style>
    .profile-image{
    vertical-align: middle;
    width: 270px;
    height: auto;
    border-radius: 5px;
}
.buttons{
    padding:50px;
}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
{% endblock %}
{% block content %}



<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>MY ACCOUNT</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
<div class="main_div">
    <div class="buttons">
    <a href="#" onclick="divVisibility('Div1');">SOUTH</a> | 
    <a href="#" onclick="divVisibility('Div2');">EAST</a> | 
    <a href="#" onclick="divVisibility('Div3');">WEST</a> | 
    <a href="#" onclick="divVisibility('Div4');">NORTH</a>
    </div>
    <div class="inner_div">
    <div id="Div1">
 
      <h2>SOUTH ZONE </h2>

<table>
  <tr>
    <th>student Name</th> 
    <th>Category</th>
    <th>Experience</th>
    <th>resume</th>
    <th>zone</th>
  </tr>
  {% for i in student_apply  %}
  {% if i.zone == 'SZ'  %}
  <tr>
    <td>{{i.student_profile}}</td>
    <td>{{i.Category}}</td>
    <td>{{i.Experience}}</td>
    <th>{{i.resume}}</th>
    <th>{{i.zone}}</th>

  </tr>
  {% endif %}
  
  {% endfor %}  
  
</table>
  
    </div>
    
    <div id="Div2" style="display: none;">
      <h2>EAST ZONE </h2>
      <table>
        <tr>
          <th>student Name</th>
          <th>Category</th>
          <th>Experience</th>
          <th>resume</th>
          <th>zone</th>
        </tr>
        {% for i in student_apply  %}
        {% if i.zone == 'EZ'  %}
        <tr>
          <td>{{i.student_profile}}</td>
          <td>{{i.Category}}</td>
          <td>{{i.Experience}}</td>
          <th>{{i.resume}}</th>
          <th>{{i.zone}}</th>
      
        </tr>
        {% endif %}
        
        {% endfor %}  
        
      </table>
    
    
    </div>
    
    <div id="Div3" style="display: none;">
      <h2>WEST  ZONE </h2>

      <table>
        <tr>
          <th>student Name</th>
          <th>Category</th>
          <th>Experience</th>
          <th>resume</th>
          <th>zone</th>
          <th>detail</th>
        </tr>
        {% for i in student_apply  %}
        {% if i.zone == 'WZ'  %}
        <tr>
          <td>{{i.student_profile}}</td>
          <td>{{i.Category}}</td>
          <td>{{i.Experience}}</td>
          <th>{{i.resume}}</th>
          <th>{{i.zone}}</th>
          <th><a href={{i.get_absolute_url}}>Detail View<a/></th>
        </tr>
        {% endif %}
        
        {% endfor %}  
        
      </table>
    </div>
    
    
    <div id="Div4" style="display: none;">
        <h2> NORTH ZONE </h2>
      <table>
        <tr>
          <th>student Name</th>
          <th>Category</th>
          <th>Experience</th>
          <th>resume</th>
          <th>zone</th>
        </tr>
        {% for i in student_apply  %}
        {% if i.zone == 'NZ'  %}
        <tr>
          <td>{{i.student_profile}}</td>
          <td>{{i.Category}}</td>
          <td>{{i.Experience}}</td>
          <th>{{i.resume}}</th>
          <th>{{i.zone}}</th>
      
        </tr>
        {% endif %}
        
        {% endfor %}  
        
      </table>
    
    
    </div>
    
  </div>
    </div>
    
    

</section>
</div>
<script>

    var divs = ["Div1", "Div2", "Div3", "Div4"];
    var visibleDivId = null;
    function divVisibility(divId) {
      if(visibleDivId === divId) {
        visibleDivId = null;
      } else {
        visibleDivId = divId;
      }
      hideNonVisibleDivs();
    }
    function hideNonVisibleDivs() {
      var i, divId, div;
      for(i = 0; i < divs.length; i++) {
        divId = divs[i];
        div = document.getElementById(divId);
        if(visibleDivId === divId) {
          div.style.display = "block";
        } else {
          div.style.display = "none";
        }
      }
    }
</script>

{% endblock %}

</div>

jobsportal/templates/homejobs.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}


<style>
.images
{
  margin-top:10px
}

.recent
{
  margin-top:10px
}
</style>
{% endblock %}

{% block content %}

<div class="images">
<img src="{% static 'images/jobportal/image.jpg' %}"  alt="not found" width="100%" height="600px"/>

</div>

<h2 align="center">job portal</h2>



<div  class="container">


<form  action="" method="POST" enctype='multipart/form-data'>

{% csrf_token %}

search jobs name:
<input type="text" name="id3" required placeholder="enter Jobs"
  oninvalid="this.setCustomValidity('enter the value ')"
  oninput="this.setCustomValidity('')"/>


search location:
<input type="text"  name="id4" required placeholder="Enter the location"
  oninvalid="this.setCustomValidity('type perfect search')"
  oninput="this.setCustomValidity('')"/>


 <input type="submit" value="submit">

</form>


{% if job %}

<div class="card-deck">
{% for i in job %}

  <div class="card">
    <img class="card-img-top" src={{i.Campy.image.url}} alt="Card image cap"/>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>

    <a href="{{i.get_absolute_url}}" class="button">check for the job </a> 
  </div>


{% endfor %}

</div>

{% else %}

<div class="recent">

<div style="text-align: center;">
<span  align="center" style="font-size:50px; border:3px solid ;"> Recent updated </span> 
</div>

</div>



{% endif %}
    



</div>
{% endblock %}

jobsportal/templates/notify.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" media="all">

<style>
  .allcover {
    background-color:#FF7F50;
  }
  
  .wrapper {
    position:relative;
    display: flex;
    width: 100%;
    height: 50vh;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    margin: 0;
    padding: 0;
  }
  
  .bell .material-icons { 
    /* font-size:12rem !important; */
    /* font-size:36px !important; */
    font-size:16rem !important;
  }
  
  .bell {
    position:relative;
    display:inline-block;  
    /* border:dashed 1px rgba(0,0,0,.25); */
    margin:0;
    padding:0;  
  }
  
  .bell .anchor {
    transform-origin:center top;
    display:inline-block;
    margin:0;
    padding:0;       
  }
  
  .bell .layer-1 {
    color:#1d1e22;
    z-index:9;
    animation: animation-layer-1 5000ms infinite;      
    opacity:0;  
  }
  
  .bell .layer-2 {
    color:#1d1e22;
    z-index:8;
    position:absolute;top:0;left:0;   
    animation: animation-layer-2 5000ms infinite;    
  }
  
  .bell .layer-3 {
    color:#333642;
    z-index:7;
    position:absolute;top:0;left:0; 
    animation: animation-layer-3 5000ms infinite;    
  }
  
  @keyframes animation-layer-1 {
    0% { transform: rotate(0deg);opacity:0; }
    8.0% { transform: rotate(0deg);opacity:0; }
    12.0% { transform: rotate(42deg);opacity:.5; }
    16.0% { transform: rotate(-35deg);opacity:.4; }
    20.0% { transform: rotate(0deg);opacity:.1; }
    23.0% { transform: rotate(28deg);opacity:.3; }
    26.0% { transform: rotate(-20deg);opacity:.2; }
    29.0% { transform: rotate(0deg);opacity:.1; }
    31.0% { transform: rotate(16deg);opacity:0; }
    33.0% { transform: rotate(-12deg);opacity:0; }
    35.0% { transform: rotate(0deg);opacity:0; }	
    37.0% { transform: rotate(-6deg);opacity:0; }
    39.0% { transform: rotate(0deg);opacity:0; }
  }
  
  @keyframes animation-layer-2 {
    0% { transform: rotate(0deg); }
    8.0% { transform: rotate(0deg); }
    12.0% { transform: rotate(42deg); }
    16.0% { transform: rotate(-35deg); }
    20.0% { transform: rotate(0deg); }
    23.0% { transform: rotate(28deg); }
    26.0% { transform: rotate(-20deg); }
    29.0% { transform: rotate(0deg); }
    31.0% { transform: rotate(16deg); }
    33.0% { transform: rotate(-12deg); }
    35.0% { transform: rotate(0deg); }	
    37.0% { transform: rotate(-6deg); }
    39.0% { transform: rotate(0deg); }
    40.0% { transform: rotate(6deg); }
    44.0% { transform: rotate(-3deg); }
    49.0% { transform: rotate(2deg);}
    55.0% { transform: rotate(0deg); }
    62.0% { transform: rotate(1deg); }
    70.0% { transform: rotate(0deg); }  
  }
  
  @keyframes animation-layer-3 {
    0% { transform: rotate(0deg);opacity:1; }
    8.0% { transform: rotate(0deg);opacity:1; }
    12.0% { transform: rotate(52deg);opacity:.5; }
    16.0% { transform: rotate(-48deg);opacity:.4; }
    20.0% { transform: rotate(0deg);opacity:1; }
    23.0% { transform: rotate(42deg);opacity:.3; }
    26.0% { transform: rotate(-30deg);opacity:.2; }
    29.0% { transform: rotate(0deg);opacity:1; }
    31.0% { transform: rotate(26deg);opacity:.15; }
    33.0% { transform: rotate(-18deg);opacity:.1; }
    35.0% { transform: rotate(0deg);opacity:1; }	
    37.0% { transform: rotate(-12deg);opacity:.8; }
    40.0% { transform: rotate(6deg);opacity:1; }
    44.0% { transform: rotate(-3deg);opacity:.8; }
    49.0% { transform: rotate(2deg);opacity:1; }
    55.0% { transform: rotate(0deg);opacity:1; }
    62.0% { transform: rotate(1deg);opacity:1; }
    70.0% { transform: rotate(0deg);opacity:1; }
  }
  
  

</style>
{% endblock %}



{% block content%}
<div class="allcover">
<div class="wrapper">
  <h1 align="center"> Alert box </h1>
    <div class="bell" id="bell-1">
      <div class="anchor material-icons layer-1">notifications_active</div>
      <div class="anchor material-icons layer-2">notifications</div>
      <div class="anchor material-icons layer-3">notifications</div> 
     
    </div>
    <p style="fontsize:70px;display:block;margin-left:10px">
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset.   
    </p>

  </div>
     
  <a href="{% url 'jobportal:allcategory' %}"<button type="button" class="btn btn-primary btn-lg btn-block">Proceed</button></a>
</div>

{% endblock %}

jobsportal/templates/specificjobs.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}


<style>

.sam{
    margin-top:50px;
}
</style>
{% endblock %}

{% block content %}
<div class="container sam">

    {{jobsdesc}}
    <br/>
    {{jobsdesc.title}}
    <br/>

    {{jobsdesc.description}}
    
    <br/>
    <br/>

{% comment %} <a href="" <button type="button" class="btn btn-success">Apply</button> </a> {% endcomment %}

{{member.usermembership}}
<form action=""  method="POST" >
    {% csrf_token %}

<input type="submit" value="Apply" />

</form>



<br/>

<br/>

</div>



{% endblock %}

jobsportal/templates/student_application.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}


<style>

    body {
        font-family: Arial, Helvetica, sans-serif;
      }
      
      .column {
        float: left;
        width: 25%;
        padding: 0 10px;
      }
      
    
      .row:after {
        content: "";
        display: table;
        clear: both;
      }
      
      /* Style the counter cards */
      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); 
        padding: 50px;
        text-align: center;
        background-color: #f1f1f1;
        margin-bottom:30px;
        margin-top:40px;
      }
      .card:hover{

      }
      
      /* Responsive columns - one column layout (vertical) on small screens */
      @media screen and (max-width: 600px) {
        .column {
          width: 100%;
          display: block;
          margin-bottom: 20px;
        }
      };
}
</style>
{% endblock %}

{% block content %}

<div class="container">
<div class="row">
{% for i in allentry %}
<div class="column">

  <div class="card">
  
      <img src="{{i.img.url}}" href="" />
      <h3>{{i.name}}</h3>
      <p>{{i.description1}}</p>
      <p>{{i.description2}}</p>
      <a href="{% url 'jobportal:modeldetail1' i.id %}"> Proceed </a> 
    </div>

  </div>


{% endfor %}

</div>
</div>
{% endblock %}

jobsportal/templates/studentdetail.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}

<style>
.sam{
    padding:50px;
}
</style>
{% endblock %}



{% block content%}


<div class="container sam">


{{students.student_profile}}
<br/>
{{students.Category}}

<br/>
{{students.Experience}}

<br/>
{{students.resume}}
<br/>
{{students.zone}}


</div>

{% endblock %}