account/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
from .views import Proceed,changeaddress,franchiseportal,certificategen,check1,show,certificate_numberss,Proceed1, subscription ,subscriptioncheck

app_name = 'account'

urlpatterns = [
     path('profile/', views.profile_view, name="profile"),
     path('mycourses/', views.MyCourses, name='mycourses'),
     path('lesson_list/<slug>/', views.LessonList, name="lesson_list"),
     path('activate/<uidb64>/<token>', views.activate,
         name='activate'),
     path('add_address',Proceed,name="address"),
     path('changeaddress',changeaddress,name="changeaddress"),
     path('franchise/',franchiseportal,name="franchise"),
     path('certificategen',certificategen,name="certificate"),
     path('check1',check1,name="check1"),
    path('show',show,name="show"),
    # path('certificate_number1/<slug:slug>',certificate_number1,name="certificate_number1"),
    path('acc/<slug:slug>',certificate_numberss,name="products1"),
    path('acc1/<slug:slug>',Proceed1,name="proceed1"),
    path('sub',subscription,name="subscription"),
    path('subscrip/<slug:slug>/',subscriptioncheck,name="subscrip")
    
]

app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

from .views import (
    add_to_cart,
    home_view,
    contact_view,
    about_view,
    letters,
    HomeView,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    success,
    failure,
    cancel,
    error404,
    viewpdf,
    organizations_trained,
    pilot_list,
    gallery,
    testimonial,
    course_detail,
    IIDLocations,
    TrainingSchedule,
    franchise,
    webinar,
    databaserror,
  CheckoutView_subscription,
    Domptest,
    successsubcription

)

app_name = 'app'

urlpatterns = [

    # URLs for navbar and homepage
    path('', home_view, name="home"),
    path('courses_list/', HomeView.as_view(), name='courses'),
    path('about/', about_view, name="about"),
    path('gallery/', gallery, name="gallery"),
    path('instructors/', TemplateView.as_view(template_name='app/instructors.html'), name="instructors"),
    path('FAQs/', TemplateView.as_view(template_name='app/faqs.html'), name="FAQs"),
    path('DGCA/', TemplateView.as_view(template_name='app/dgca.html'), name="DGCA"),
    path('certification/', TemplateView.as_view(template_name='app/certification.html'), name="certification"),
    path('pilot-list/', pilot_list, name="pilot-list"),
    path('drone-jobs/', TemplateView.as_view(template_name='app/about_us.html'), name="drone-jobs"),
    path('testimonials/', testimonial, name="testimonials"),
    path('news-and-media/', TemplateView.as_view(template_name='app/news-events.html'), name="news-and-events"),
    path('infrastructure/', TemplateView.as_view(template_name='app/infrastructure.html'), name="infrastructure"),
    path('organizations-trained/', organizations_trained, name="organizations"),
    path('contact/', contact_view, name="contact"),
    path('satisfactory-letters/', letters, name="letters"),
    path('error/', error404, name="error"),
    path('terms-and-conditions/', TemplateView.as_view(template_name='app/terms-conditions.html'), name="t-c"),
    path('indemnity/', TemplateView.as_view(template_name='app/indemnity.html'), name="indemnity"),
    path('privacy/', TemplateView.as_view(template_name='app/privacy.html'), name="privacy"),
    path('cookies/', TemplateView.as_view(template_name='app/cookies.html'), name="cookies"),
    #path('franchise/', TemplateView.as_view(template_name='app/franchise.html'), name="franchise"),
    path('franchise/', franchise, name="franchise"),
    
    # URLs for Courses, Cart, Payment and pdf
    path('course/<slug>/', course_detail, name='course-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('success/', success, name='order.success'),
    path('failure/', failure, name='order.failure'),
    path('cancel/', cancel, name='order.cancel'),

    path('pdf_view/<slug:tid>', viewpdf, name="pdf_view"),

    path('pdf_template/', TemplateView.as_view(template_name='app/invoice.html')),

    path('iid-locations',IIDLocations.as_view(),name="iid-loc"),
    path('training-schedule',TrainingSchedule.as_view(),name="tr-schedule"),
    path('webinar-events',webinar, name="webinar"),
    path("databaserror",databaserror,name="databaserror"),

    path("CheckoutView_subscription/<str:pk>/",CheckoutView_subscription.as_view(),name="CheckoutView_subscription"),
    path('certificationform',Domptest,name="Domptest"),
    path('subscription/order',successsubcription,name="order.success1")
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_view, logout_view
from django.contrib.auth import views as auth_views  # for pass change and reset views
from django.conf import settings  # for profile pic
from django.conf.urls.static import static  # for profile pic

from django.views.defaults import page_not_found, permission_denied, bad_request, server_error
from django.http import Http404
from django.views.generic.base import RedirectView
from django.views.csrf import csrf_failure
from Blog.views  import ModelNameDetail


urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('ss',include('jobsportal.urls',namespace='jobportal')),
    path('store/', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    # path('', include('django.contrib.auth.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('captcha/', include('captcha.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('404/', page_not_found, {'exception': Http404()}),
    path('403/', permission_denied, {'exception': Http404()}),
    path('500/', server_error),
    path('400/', bad_request, {'exception': Http404()}),
    path('blog/',include('Blog.urls',namespace='Blog')),
    path('<slug:slug>/',ModelNameDetail.as_view(),name="model_detail"),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/app/Training.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}
<title>Training Schedule - Indian Institute of Drones | Best Drone Pilot Training India</title>
<meta name="keywords" content="drone pilot courses, online drone courses, fixed wing drone pilot training, multirotor drone pilot training, dgca drone pilot courses">
<meta name="description" content="Indian Institute of Drones. Become a UAV Pilot. Training Schedule for Drone Pilot Courses. Explore Professional Courses for UAVs/Drones">

<style>
    .sidebar{
        background-color: #34495e;
        display: block;
        padding: 3% 4%!important;
    }
    .sidebar .ques{
        font-size: 1.8rem;
        color: #fff;
    }
    .head{
        color: #b9b9b9;
        font-size: 1.5rem;
    }
    .head span{
        border-bottom: 1px solid #dedede;
    }
    .info{
        color: #fff;
        font-size: 1.1rem;
    }
    @media only screen and (max-device-width: 768px) {
        .head{font-size: 0.9rem}
        .info{font-size: 1.2rem}
        .sidebar{padding: 3% 2%!important;}
    }
    .btnn-city{
        border-radius: 25px!important;
        border: 1px solid #000!important;
        padding: 10px 50px;
    }
    .dropdown-menu-center{width: 250px}
    .training-card{display: none}
    .cont-det{display:none}
    .details-card{
        min-height: 180px;
        padding: 10px 15px;
    }
    .date-city{
        min-height: 150px;
        background-color: #283B62;
        color: #fff;
        display: flex;
        align-items: center;
    }
    .date-city h1{padding-left: 15px}
    .date-city h1{font-size: 170%}
    .date-city h1 span{font-size: 80%}
    .course-details{
        background-color: #f4f4f4!important;
    }
    .course-details h2{
        font-size: 150%;
        padding-top: 20px;
        padding-bottom: 10px;
    }
    .course-details ul{
        padding-left: 20px;
    }
    .btn-cta{
        margin-bottom: 8px;
    }
</style>
{% endblock %}

{% block content %}

<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>TRAINING SCHEDULE</h1>
            </div>
        </div>
    </div>
</div>

<section class="training-schedule">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="dropdown show text-center my-3">
                        <a class="btn btn-secodary dropdown-toggle btnn-city" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select a City near you
                        </a>
                        <div class="dropdown-menu dropdown-menu-center" aria-labelledby="dropdownMenuLink">
                            {% for i in list3 %}
                            <a class="dropdown-item sel{{i.city}}" href="#" id="">{{i.city}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    
                    <div id="map" class="py-3">
                        <iframe src="https://www.google.com/maps/d/embed?mid=1E1KhfpgOlHZc63BlHAF5J2ek1vK-hrz2" width="100%" height="350px"></iframe>
                    </div>
                    
                    
                    {% for i in object_list %}
                    <div id="" class="training-card city{{i.city}}">
                        <div class="row details-card">
                            <div class="col-sm-5 date-city">
                                <h1>
                                    {{i.date}} <br>
                                    <span>{{i.city}}</span>
                                </h1>
                            </div>
                            <div class="col-sm-7 course-details" >
                                <center><h2>{{i.coursename}}</h2></center>
                                <ul>
                                    <li>{{i.callme}}</li>
                                    <li>{{i.callme2}}</li>
                                </ul>
                                <center><a href="course/{{i.sum}}" class="btn btn-success btn-cta">Enroll Now</a></center>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <div class="col-sm-4 sidebar">
                    <h4 class="ques text-center">
                        Got Questions?<br>
                        Get in touch
                    </h4>

                    <div class="cont-hq">
                        <h4 class="head pt-5"><span>HEADQUARTERS</span></h4>
                        <h4 class="info pt-2">C - 270, Pocket C, Sector - 71,<br>Noida - 201307</h4>
                        <h4 class="head pt-5"><span>PHONE</span></h4>
                        <h4 class="info pt-2">+91-8074611720</h4>
                        <h4 class="head pt-5"><span>EMAIL</span></h4>
                        <h4 class="info pt-2">director@iiodrones.com</h4>
                    </div>
                    {% for s in list3 %}
                    <div class="cont-det con{{s.city}}">
                        <h4 class="head pt-5"><span>ADDRESS</span></h4>
                        <h4 class="info pt-2">{{s.Address}}</h4>
                        <h4 class="head pt-5"><span>PHONE</span></h4>
                        <h4 class="info pt-2">{{s.Phone1}}</h4>
                        {% if i.Phone2 %}
                        <h4 class="info pt-2">{{s.Phone2}}</h4>
                        {% endif %}
                        <h4 class="head pt-5"><span>EMAIL</span></h4>
                        <h4 class="info pt-2">{{s.email1}}</h4>
                        {% if i.email2 %}
                        <h4 class="info pt-2">{{s.email2}}</h4>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function(){
        {% for i in list3 %}
        $(".sel{{i.city}}").click(function(){
            $("#map").hide(300);
            $(".cont-hq").hide(300);
            {% for i in show %}
            $(".city{{i.city}}").hide(600);
            $(".con{{i.city}}").hide(600);
             {% endfor %}
             $(".city{{i.city}}").show(600);
             $(".con{{i.city}}").show(600);
        });
        {% endfor %}
    });     
</script> 


{% endblock %}

app/templates/app/certification.html
{% extends 'app/base.html' %}
{% load static %}
{% block extra_head %}
<title>Certifications - Indian Institute of Drones | Certified Instructors</title>
<meta name="keywords" content="drone pilot courses, online drone courses, fixed wing drone pilot training, multirotor drone pilot training, Drone Training FTO">
<meta name="description" content="IID is proud to be associated with DGCA Approved Drone Training Institute Pioneer Flying Academy (FTO) for Small Category Drone Training. Certificates of Indian Institute of Drones. Get Certified by Ex - UAV Military Instructors. Become a UAV Pilot.">

<style>

    .certification img{
        display: block;
        margin-left: auto;
        margin-right: auto;
        height: auto;
        width: 80%;
        border: 1px solid;
    }

    .certification p{
        text-align: center;
        font-weight: bold;
        margin-top: 5px;
    }

    .cert{
        margin-top: 10px;
        padding-bottom: 5px;
    }
    .zoom{
        text-decoration: none !important;
        color: #000;
    }
    .zoom:hover{
        color: #ff6830;
    }
</style>
{% endblock %}

{% block content %}

<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>CERTIFICATION</h1>
            </div>
        </div>
    </div>
</div>

<section class="certification">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/John-instructor.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/John-instructor.jpg' %}" alt="Satisfactory Letter from DGCA">
                    <p>DGCA Approved RPAS Trainer Certificate of Lt Cdr John Livingstone</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/Ram-instructor.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/Ram-instructor.jpg' %}" alt="Satisfactory Letter from DGCA">
                    <p>DGCA Approved RPAS Trainer Certificate of Ram Sarath Kumar</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/PFA Letter.png' %}" class="zoom">
                        <img src="{% static 'images/Certification/PFA Letter.jpg' %}" alt="Satisfactory Letter from DGCA">
                    <p>Partnernship with DGCA Approved FTO - Pioneer Flying Academy for conducting Drone Training</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'docs/JR5 Exemption.pdf' %}" class="zoom">
                        <img src="{% static 'images/Certification/JR5 Exempt.jpg' %}" alt="Satisfactory Letter from DGCA">
                    <p>Johhnnette-JR5 Exempted by MoCA for conducting Drone Training</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/sample_certificate.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/sample_certificate.jpg' %}" alt="Your Certificate" width="80%">
                    <p>Student Certificate</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/pilot-card.png' %}" class="zoom">
                        <img src="{% static 'images/Certification/pilot-card.png' %}" alt="Your Certificate" width="80%">
                    <p>Student Pilot Card</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/dgca_letter_1.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/dgca_letter_1.jpg' %}" alt="Satisfactory Letter from DGCA">
                    <p>Satisfactory Letter from DGCA</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/dgca_letter_2.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/dgca_letter_2.jpg' %}" alt="Committe for UAS Manufacturing  by DCGA">
                    <p>Committe for UAS Manufacturing  by DGCA</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/Franchise certificate.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/Franchise certificate.jpg' %}" alt="Franchise Certificate" width="80%">
                    <p>Franchise Certificate</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/Instructor_certificate.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/Instructor_certificate.jpg' %}" alt="IID Instructor  Certificate" width="80%">
                    <p>Air Force School Certificate</p></a>
                </div>
                <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/IID_reg.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/IID_reg.jpg' %}" alt="IID Registration Certificate">
                     <p>IID Registration Certificate</p></a>
                </div>
                <!-- <div class="col-sm-6 cert">
                    <a href="{% static 'images/Certification/Instructor_certificate.jpg' %}" class="zoom">
                        <img src="{% static 'images/Certification/Instructor_certificate.jpg' %}" alt="IID Instructor  Certificate" width="80%">
                    <p>IID Instructor  Certificate</p></a>
                </div> -->
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/templates/app/domp.html
{% load static %}

<html>


<head>

<link href="https://fonts.googleapis.com/css2?family=Cherish&family=Open+Sans+Condensed:wght@300&family=Padauk&family=Stick+No+Bills:wght@200&display=swap" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<style>

@frame h1
{
  top:50pt;
}


@page 
{ 

size: letter landscape; margin: 0cm;

}
     
h1 {
  position: relative;
  top:50pt;
}

.image{
    border-bottom:10px solid #00264C;
    padding-bottom:20px;
    
}


.Text
{
    margin-top: 10px;
    font-weight:20px;
    font-family:Times-Roman;
    color:#000000;
}

.Text1
{
text-align:center;
font-size:22px;

font-family:Courier;
}

.Text2
{   
margin-top:4px;
font-family:Times-BoldItalic;
text-decoration: underline;
text-decoration-color: black;
}
h1 {
  left: 50pt; width: 512pt; top: 90pt; height: 632pt;
  position:absolute;
  height:196.373328px;

}



</style>

</head>


<body>

    <div >
     
        <center>
        <img src="C:\Users\Administrator\Desktop\iidcurrent2\IID-New-Website\new.png"/>
        
       </center>



        <br/>
        <br/>
        <div class="Text"> 
        <center>
        <span style="font-size:40px; text-align=center; "><b>THIS TO CERTIFY THAT </b></span>
        </center>

        
        </div>

        <br/>
        <div class="Text2"> 
        <center>
        <span style="font-size:25px; text-align=center; color:orange;"><b>{{certificate.first_name|upper}} {{certificate.last_name|upper}} <b></h1>
        </center>

        
        
        </div>

        <br/>
        <div class="Text1">
            
           <span style="color:#000000;"> <B>IS  A DRONE OPERATIONS AND MANAGEMENT PROFESSIONAL (DOMP) WHO HAS SUCCESSFULLY <br/>
            COMPLETED THE ONLINE CERTICATION COURSE ON {{date}} <B><span>
       
       </div>    


<br/>
<br/>
<table id="customers">
  <tr>
    
    <td style="text-align:center"><img src="C:\Users\Administrator\Desktop\iidcurrent2\new1.png" width=150px height=150px; /><br>iid numbers <br/> no of certificate</td>
    <td>  </td>
    <td> </td>
    <td> </td>
    <td style="text-align:left"> <img src="C:\Users\Administrator\Desktop\iidcurrent2\Capture.png" width=450px height=300px; /> </td>
  </tr>
 
  


 
 </table>

  

  
</div>




</body>

</html>

app/templates/app/safe.html
{% load static %}

<style>
    body{
        background-color: #fff;
    }

    .thanks{
        font-size: 1.8em;
        color: #14d303;
        font-weight: bold;
        text-align: center;
    }

    .status, .transc {
        font-size: 1.2em;
        text-align: center;
    }

    .payment {
        font-size: 1.2em;
        text-align: center;
    }

    .ctabtn{
        margin: 5px 5px!important;
    }

    @media only screen and (max-device-width: 480px) {
        .payment {
        font-size: 0.9em;
    }

    }
</style>

<html>
    <head>
        <title>Transaction Successful | Indian Institute of Drones</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon/apple-icon-57x57.png' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/apple-icon-60x60.png' %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon/apple-icon-72x72.png' %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon/apple-icon-76x76.png' %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon/apple-icon-114x114.png' %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-icon-120x120.png' %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon/apple-icon-144x144.png' %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon/apple-icon-152x152.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-icon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
        <meta name="theme-color" content="#ffffff">
</head>
<body>

    <div style="display:none">
        <input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}">
    </div>

    <br><br>
    <div class="container-fluid">
        <div class="container">
            <div class="row my-4">
                <div class="col-sm-12 text-center pt-6 mt-4">
                    <img src="{% static 'images/Logo/IID_logo.jpg' %}" alt="IID Logo" width="20%">
                </div>
            </div>
            
            <div class="row my-4">
                <div class="col-sm-12">
                    <h1 class="thanks pb-3">Thank You! Online Certificate </h1>
          
                    <h2 class="transc">Transaction ID: <b>{{ transaction_id }}</b></h2>
					<h3 class="payment">We have received a payment of <b>₹ {{ sales.price}} </b></h3>
                </div>
                <br>
                <br>
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="ordsum">Successful genrate certificate</th>
                            </tr>
                        </thead>
                        <tbody>
                         
                            <tr>
                                <td><i class="fa fa-angle-right"></i> {{item1.item.title}}</td>
                                <td>{{sales.name}}</td>
                                <td>{{sales.certificate_number}}</td>
                                <td>{{sales.Dob}}</td>
                                <td>{{sales.category}}</td>
                                
                            </tr>
                           
                           
                        </tbody>
                    </table>
                    
                    <br>
                    <center>
                    <a class="btn btn-primary ctabtn" href="{{sales.show}}">Download certificate</a> 
                        <a class="btn btn-primary ctabtn" href="{% url 'account:certificate' %}">Again Certificate</a>                    
                        <a class="btn btn-primary ctabtn" href="{% url 'app:home' %}">Back to Home</a> 
                    </center>
                   
    </div>
    </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</body>
</html>

app/templates/app/terms-conditions.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_head %}
<title>Terms and Conditions - Indian Institute of Drones | Military Certified Drone Pilot Instructors</title>
<meta name="keywords" content="drone pilot courses, online drone courses, fixed wing drone pilot training, multirotor drone pilot training">
<meta name="description" content="Terms and Conditions for using the website of Indian Institute of Drones.">

<style>
    .refund-policy{
        background-color: #fff;
        color: #000;
    }
    .refund-policy li{
        padding: 5px 0px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>Terms and Conditions</h1>
            </div>
        </div>
    </div>
</div>
    
<section class="refund-policy py-4">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h3>Refund Policy for Classroom Courses</h3>
                    <ul>
                       <li>All the classroom (or offline) courses purchased on the IID website are <strong>non-refundable</strong>. No refund will be granted in any circumstances.</li> 
                       <li>If you are unable to attend the course on the designated date, then you can join any one of the upcoming batches scheduled (up to 1 month from the date of purchase).</li> 
                       <li>Please contact us via the provided methods to get your batch rescheduled.</li> 
                    </ul>
                    <br>
                    <h3>Refund Policy for Online Courses</h3>
                    <ul>
                        <li>All the Online courses available on IID website are <strong>non-refundable</strong>. Once the course has been purchased by the user, no refund will be granted regardless of the reason. </li> 
                        <li>All the online courses have been tested extensively on different types of devices and browsers. If you are facing any issues in accessing the course content, or any other problem, you can contact us for assistance.</li>
                    </ul>
                    <br>
                    <p>If you have any questions or queries regarding refund, please get in touch with us through either of the methods:</p>
                    <ul>
                        <li>Write to us: director@iiodrones.com</li>
                        <li>Visit the <a title="Go to Contact Page" href="{% url 'app:contact' %}">Contact</a> Page </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}