app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

from .views import (
    add_to_cart,
    home_view,
    contact_view,
    about_view,
    letters,
    HomeView,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    success,
    failure,
    cancel,
    error404,
    viewpdf,
    organizations_trained,
    pilot_list,
    gallery,
    testimonial,
    course_detail,
    IIDLocations,
    TrainingSchedule,
    franchise,
    webinar,
    databaserror,
  CheckoutView_subscription,
    Domptest,
    successsubcription

)

app_name = 'app'

urlpatterns = [

    # URLs for navbar and homepage
    path('', home_view, name="home"),
    path('courses_list/', HomeView.as_view(), name='courses'),
    path('about/', about_view, name="about"),
    path('gallery/', gallery, name="gallery"),
    path('instructors/', TemplateView.as_view(template_name='app/instructors.html'), name="instructors"),
    path('FAQs/', TemplateView.as_view(template_name='app/faqs.html'), name="FAQs"),
    path('DGCA/', TemplateView.as_view(template_name='app/dgca.html'), name="DGCA"),
    path('certification/', TemplateView.as_view(template_name='app/certification.html'), name="certification"),
    path('pilot-list/', pilot_list, name="pilot-list"),
    path('drone-jobs/', TemplateView.as_view(template_name='app/about_us.html'), name="drone-jobs"),
    path('testimonials/', testimonial, name="testimonials"),
    path('news-and-media/', TemplateView.as_view(template_name='app/news-events.html'), name="news-and-events"),
    path('infrastructure/', TemplateView.as_view(template_name='app/infrastructure.html'), name="infrastructure"),
    path('organizations-trained/', organizations_trained, name="organizations"),
    path('contact/', contact_view, name="contact"),
    path('satisfactory-letters/', letters, name="letters"),
    path('error/', error404, name="error"),
    path('terms-and-conditions/', TemplateView.as_view(template_name='app/terms-conditions.html'), name="t-c"),
    path('indemnity/', TemplateView.as_view(template_name='app/indemnity.html'), name="indemnity"),
    path('privacy/', TemplateView.as_view(template_name='app/privacy.html'), name="privacy"),
    path('cookies/', TemplateView.as_view(template_name='app/cookies.html'), name="cookies"),
    #path('franchise/', TemplateView.as_view(template_name='app/franchise.html'), name="franchise"),
    path('franchise/', franchise, name="franchise"),
    
    # URLs for Courses, Cart, Payment and pdf
    path('course/<slug>/', course_detail, name='course-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('success/', success, name='order.success'),
    path('failure/', failure, name='order.failure'),
    path('cancel/', cancel, name='order.cancel'),

    path('pdf_view/<slug:tid>', viewpdf, name="pdf_view"),

    path('pdf_template/', TemplateView.as_view(template_name='app/invoice.html')),

    path('iid-locations',IIDLocations.as_view(),name="iid-loc"),
    path('training-schedule',TrainingSchedule.as_view(),name="tr-schedule"),
    path('webinar-events',webinar, name="webinar"),
    path("databaserror",databaserror,name="databaserror"),

    path("CheckoutView_subscription/<str:pk>/",CheckoutView_subscription.as_view(),name="CheckoutView_subscription"),
    path('certificationform',Domptest,name="Domptest"),
    path('subscription/order',successsubcription,name="order.success1")
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_view, logout_view
from django.contrib.auth import views as auth_views  # for pass change and reset views
from django.conf import settings  # for profile pic
from django.conf.urls.static import static  # for profile pic

from django.views.defaults import page_not_found, permission_denied, bad_request, server_error
from django.http import Http404
from django.views.generic.base import RedirectView
from django.views.csrf import csrf_failure
from Blog.views  import ModelNameDetail


urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('ss',include('jobsportal.urls',namespace='jobportal')),
    path('store/', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    # path('', include('django.contrib.auth.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('captcha/', include('captcha.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('404/', page_not_found, {'exception': Http404()}),
    path('403/', permission_denied, {'exception': Http404()}),
    path('500/', server_error),
    path('400/', bad_request, {'exception': Http404()}),
    path('blog/',include('Blog.urls',namespace='Blog')),
    path('<slug:slug>/',ModelNameDetail.as_view(),name="model_detail"),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include


from .views import  * 


app_name="store"


urlpatterns = [

     path('',Home.as_view(),name='stores'),
     path('products/<slug>/',ItemDetailView.as_view(),name="products"),
     path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"),
     path('order-summary',OrderSummaryView.as_view(),name="order-summary"),
     path('remove_item_from_cart/<slug>/',remove_item_from_cart,name="remove_item_from_cart"),
     path('remove-from-cart/<slug>/',remove_from_cart,name="remove"),
     path('myorders/',active_order,name="active_order")


   
]

store/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from ckeditor.fields import RichTextField
from payu.models import Transaction
from account.models import Account
from django.core.files.images import get_image_dimensions
from django.core.exceptions import ValidationError


class Item(models.Model):
    title=models.CharField(max_length=100,verbose_name="Product Name")
    price=models.FloatField()
    description1=models.CharField(max_length=200,blank=True,null=True)
    description2=RichTextField(default="Product Description",null=True,blank=True)   
    slug=models.SlugField(blank=True,null=True)

    images=models.ImageField(upload_to="",null=True,blank=True,help_text='Image resolution must be 600px x 600px')

    class Meta:
        verbose_name = 'Product'
    
    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        
        return reverse("store:products", kwargs={"slug": self.slug})

    def add_to_cart(self):

        return reverse("store:add-to-cart",kwargs={'slug':self.slug})
    
    def get_remove_from_cart(self):
        return reverse("store:remove",kwargs={'slug':self.slug})

    def clean(self):
        w,h=get_image_dimensions(self.images)
        
        
        file_size=self.images.file.size

        if file_size >50000:
            raise ValidationError("Size of the image must be > 50 KB and < 2 MB")

        if file_size >2000000:
             raise ValidationError("Size of the image must be < 2 MB and > 50 KB")

        if w<600 or w>600 and h<600 or h>600:
            raise ValidationError("Image resolution must be 600px x 600px")

class KingOrderItems(models.Model):

    item=models.ForeignKey(Item,on_delete=models.CASCADE,null=True,blank=True,related_name="orderitems")
    quantity=models.IntegerField(default=1)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=True,related_name="user2")
    ordered=models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Ordered List'
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}" 
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):

        return self.get_total_item_price()


CATEGORY_CHOICES1=(

    ('Processing','Processing'),
    ('Completed','Completed'),
    ('Active','Active'),
)


class KingOrder(models.Model):
    user=models.ForeignKey(Account,on_delete=models.CASCADE,related_name="user3",blank=True, null=True)
    items=models.ManyToManyField(KingOrderItems,related_name="orders")
    ordered_date=models.DateTimeField(blank=True, null=True)
    ordered=models.BooleanField(default=False)
    transaction = models.ForeignKey(Transaction, on_delete=models.SET_NULL, blank=True, null=True)
    invoice = models.FileField(upload_to='Invoice/', null=True, blank=True)
    billing_address=models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True)
    shipment=models.CharField(choices=CATEGORY_CHOICES1,max_length=100,default="Active",blank=True,null=True)
    Tracking_field=models.URLField(blank=True,null=True)    
       
    def __str__(self):
        return str(self.user)
    
    def get_total(self):
        total=0

        for i in self.items.all():
            total+=i.get_total_item_price()

        return total
    
    class Meta:
        verbose_name = 'Ordered Product'
        verbose_name_plural = 'Ordered Products'


class BillingAddress(models.Model):
    
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,unique=True,null=True,blank=True)        
    address_1=models.CharField(max_length=200,null=True)
    address_2=models.CharField(max_length=200,null=True)
    city=models.CharField(max_length=100,null=True)
    state=models.CharField(max_length=100,null=True)
    zip_code=models.CharField(max_length=100,null=True)
    check=models.BooleanField(default=True)
    
    def __str__(self):
    
        return str(self.name)

    class Meta:
        verbose_name = 'Billing Address'
        verbose_name_plural = 'Billing Address'

store/forms.py
from django import forms
from django_countries.fields import CountryField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column


STATES = (("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry"))

class CheckoutForm(forms.Form):
  
    address_1 = forms.CharField(
        label='Address Line 1',
        widget=forms.TextInput(attrs={'placeholder': '123, Maxim Apartments,' ,},
       )
    )
    address_2 = forms.CharField(
        label='Address Line 2',
        widget=forms.TextInput(attrs={'placeholder': 'Block E, Main Street',})
    )
    city = forms.CharField(widget=forms.TextInput(attrs={}))
    state = forms.ChoiceField(choices=STATES)
    zip_code = forms.CharField(label='Pincode',widget=forms.TextInput(attrs={}))
  

store/views.py
from django.shortcuts import render
from django.db import IntegrityError

# Create your views here.
from django.shortcuts import render
from .models import *
from django.views.generic import ListView,DetailView,View
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404,redirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(ListView):
    model=Item
    template_name = "catalogue.html"
    paginated_by=1


class ItemDetailView(DetailView):
    #login_url = '/login/'
    model=Item
    template_name="product.html"
    

def add_to_cart(request,slug):

    current_user=request.user
    if str(current_user) == 'AnonymousUser':
        request.session['productslug'] = str(slug)

        return redirect("login")
    
    item=get_object_or_404(Item,slug=slug)

    order_item,created=KingOrderItems.objects.get_or_create(item=item,user=request.user,ordered=False)

    order_qs=KingOrder.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        order=order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity+=1
            messages.info(request,"Item quantity updated")
            order_item.save()
        else :
            messages.info(request,"This item was added to your cart.")
            order.items.add(order_item)
    else:
        ordered_date=timezone.now()
        order=KingOrder.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"Item quantity updated  ")

    return redirect("app:order-summary")


class OrderSummaryView(View):
    def get(self,*args,**kwargs):

            order=KingOrder.objects.get(user=self.request.user,ordered=False)
            context={
                'objects':order
            }
            return render(self.request,'order_summary.html',context) 
    

@login_required
def remove_item_from_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)

    order_qs=KingOrder.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        order=order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            
            order_item=KingOrderItems.objects.filter(
                item=item,user=request.user,ordered=False)[0]


            if order_item.quantity>1:
                order_item.quantity-=1
                order_item.save()
                messages.info(request,"Item quantity updated")
            else:
                order.items.remove(order_item)

            return redirect('app:order-summary')
        else:
 
            return redirect("app:order-summary")
           
    else:
        messages.info(request,"You do not have an active order")
        
    return redirect("app:order-summary")


@login_required
def remove_from_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)

    order_qs=KingOrder.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        order=order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            
            order_item=KingOrderItems.objects.filter(
                item=item,user=request.user,ordered=False)[0]

            order_item.quantity=1
            order_item.save()           
            order.items.remove(order_item)
            messages.info(request,"This Item was removed from your cart")
            return redirect("app:order-summary")
        else:
            messages.info(request,"This item was removed from your cart ")
            return redirect("store:products",slug=slug)
           
    else:
        messages.info(request,"You do not have an active order")
        return redirect("store:products",slug=slug)
    return redirect("store:products",slug=slug)




def active_order(request):

    try :
        order_qs=KingOrder.objects.filter(user=request.user,ordered=True).order_by('-ordered_date')
        
        if order_qs:
            return render(request,"orderhistory.html",{"order_qs":order_qs ,"show":True})
        
        else:
            messages.info(request,"Your order history is empty!")
            return render(request,"orderhistory.html",{"show":False})
    
    except:
        messages.info(request,"Your order history is empty!")
        return render(request,"orderhistory.html",{"show":False})    

store/templates/activeorder - Copy.html
{% extends 'app/base.html' %}
{% block extra_head %}

{% load static %}
<title>Order History - Indian Institute of Drones</title>

<style>
  .item_pic{
    padding: 2px 1px;
  }
</style>


{% endblock %}

{% block content %}

<div class="container-fluid univ-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>Order History</h1>
            </div>
        </div>
    </div>
</div>

 

{% if show %}

<div class="container-fluid">
  <div class="container">
      <div class="row">
          <div class="col-sm-12">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">Ordered Date </th>
                  <th scope="col">Items</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Item Price</th>
                  <th scope="col">Order Amount</th>
                  <th scope="col">Status</th>
                  <th scope="col">Tracking URL <i class="fas fa-external-link-alt"></i></th>
                </tr>
              </thead>
              <tbody>
                {% for i in order_qs  %}
                <tr>
                  <td>{{i.ordered_date}}</td>
                  <td>
                    {% for y in i.items.all %}
                    <img class="item_pic" src= "{{y.item.images.url}}" alt="{{y.item.title}}" width="40px" height="30px">
                    {{y.item.title}}<br>
                    {% endfor %} 
                  </td>
                  <td>
                    {% for y in i.items.all %}
                    {{y.quantity}}<br>
                    {% endfor %} 
                  </td>
                  <td>
                    {% for y in i.items.all %}   
                    ₹ {{y.get_total_item_price}}<br>
                    {% endfor %}
                  </td>
                  <td>
                    ₹ {{i.get_total}}
                  </td>
                  <td>
                    {{i.shipment}}
                  </td>
                  <td>
                    {% if i.Tracking_field %}
                    <a href="{{i.Tracking_field}}" style="font-size: 0.7em;" target="_blank" rel="noreferrer">{{i.Tracking_field}}</a>
                    {% else %}
                    --
                    {% endif %}
                  </td>
                </tr>
                {% endfor %} 
              </tbody>
            </table>
          </div>
      </div>
  </div>
</div>

{% else %}

<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <img class="center" src="{% static 'images/book.png' %}"  width="400px" height="400px">
        <h3 align="center">you do not have active order </h3>
        <a href="{% url "store:stores"  %}"><button align="center" class="btn btn-primary hide2" type="submit">Products </button></a>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% endblock %}

<!-- 
<div class="container">

  <img class="center" src="{% static 'images/book.png' %}"  width="400px" height="400px" />
  
  <br/>
  
  
  <div class"None" align="center">
  
  <h3 align="center">you do not have active order </h3>
  
  {% comment %}  {% endcomment %}
  <a href="{% url "store:stores"  %}"><button align="center" class="btn btn-primary hide2" type="submit">Products </button></a>
  
  
  </div>
  
  
  
  </div>
  
  {% endif %}


<div class="container">
  <br/>
 <div class="shakti">
 <table class="table table-striped">
  <thead>
    <tr>
     <th scope="col">Ordered Date </th>
      <th scope="col">Items </th>
      <th scope="col">quantity</th>
      <th scope="col">Amount </th>
      <th scope="col">Total Amount </th>
      <th scope="col">Status </th>
      <th scope="col">Tracking </th>
    </tr>
  </thead>
    

  <tbody>

 
  {% for i in order_qs  %} 

  <tr>
   <td>{{i.ordered_date}}</td>
        
        <td>
        {% for y in i.items.all %}
    
     <img src= "{{y.item.images.url}}" alt=""  width="50px" height="20px" />
     {{y.item.title}}
    

    <br/>
    
    {% endfor %} 
    </td>
    <td >
    {% for y in i.items.all %}

    {{y.quantity}}

    <br/>
  {% endfor %}

  </td>  
  <td> 
  
  {% for y in i.items.all %}

    ₹ {{y.get_total_item_price}}

    <br/>

  {% endfor %}

</td>
  <td>₹ {{i.get_total}}</td>

  

  <td>{{i.shipment}} </td>

  {% if i.Tracking_field %}

  <td><a  href="{{i.Tracking_field}}" >{{i.Tracking_field}} </a></td>

  {% else %}

  <td> -- <td> 

  {% endif %}
  
  </tr>
   {% endfor %} 
    
 </tbody>
  
</table>

</div>

</div>

{% comment %} 
<div class="123" />


</div> {% endcomment %}


{% else %}


<div class="container">

<img class="center" src="{% static 'images/book.png' %}"  width="400px" height="400px" />

<br/>


<div class"None" align="center">

<h3 align="center">you do not have active order </h3>

{% comment %}  {% endcomment %}
<a href="{% url "store:stores"  %}"><button align="center" class="btn btn-primary hide2" type="submit">Products </button></a>


</div>



</div>

{% endif %}


<br/>
</div>
 -->

store/templates/orderhistory.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_head %}
<title>Order History - Indian Institute of Drones</title>

<style>
  .table {
    margin-top: 20px !important;
    margin-bottom: 2px !important;
  }

  .rowone {
    box-shadow: 0rem 0.3rem 1rem rgba(88, 88, 88, 0.2);
  }

  .rowtwo {
    box-shadow: 0rem 1rem 2.5rem rgba(88, 88, 88, 0.5);
  }

  .blrow {
    border-top: 0px !important;
  }

  @media only screen and (max-device-width: 480px) {
    .cont-fluid {
      padding: 2px 8px !important;
    }

    .cont-cont {
      padding: 2px 8px !important;
    }

    .cont-col {
      padding: 2px 4px !important;
    }

    .table {
      font-size: 0.5rem;
    }

    .datacol {
      padding: 6px 6px !important;
      margin: 0px !important;
    }
  }
</style>


{% endblock %}

{% block content %}

<div class="container-fluid univ-header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h1>Order History</h1>
      </div>
    </div>
  </div>
</div>

{% if show %}
<div class="container-fluid cont-fluid">
  <div class="container cont-cont">
    <div class="row">
      <div class="col-sm-12 cont-col">
        <table class="table">
          <thead>
            <tr class="">
              <th class="datacol">Item Name</th>
              <th class="datacol" style="text-align: center;">Quantity</th>
              <th class="datacol" style="text-align: right;">Item Price</th>
              <th class="datacol" style="text-align: right;">Total Price</th>
            </tr>
            <tr>

            </tr>
          </thead>
          <tbody>
            {% for i in order_qs %}

            <tr class="rowone">
              <td class="datacol">
                {% for y in i.items.all %}
                <i class="fas fa-angle-right"></i> {{y.item.title}}<br>
                {% endfor %}
              </td>

              <td class="datacol" align="center">
                {% for y in i.items.all %}
                {{y.quantity}}<br>
                {% endfor %}
              </td>

              <td class="datacol" align="right">
                {% for y in i.items.all %}
                ₹ {{y.get_total_item_price}}<br>
                {% endfor %}
              </td>

              <td class="datacol" align="right">₹ {{i.get_total}}</td>
            </tr>

            <tr class="rowtwo">
              <td class="datacol blrow" colspan="1"><b>Ordered Date:</b><br>{{i.ordered_date}}<br></td>
              <td class="datacol blrow" align="center"><b>Order Status:</b><br>{{i.shipment}}<br></td>
              {% if i.Tracking_field %}
              <td class="datacol blrow" colspan="1" align="center"><b>Tracking URL:</b><br>{{i.Tracking_field}}<br></td>
              {% else %}
              <td class="datacol blrow" colspan="2" align="center"><b>Tracking URL:</b><br>--</td>
              {% endif %}
            </tr>

            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% else %}

<div class="container-fluid">
  <div class="container">
    <div class="row py-4">
      <div class="col-sm-12 text-center">
        <img src="{% static 'images/Icons/empty-cart.png' %}" width="15%" height="auto">
        <h1 style="font-size: 1.7em; padding: 15px 1px;">Your cart is empty!</h1>
        <a href="{% url 'store:stores' %}"><button class="btn btn-primary" type="submit">Browse Our Product
            Catalogue</button></a>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% endblock %}

store/templates/product.html
{% extends 'app/base.html' %}
{% load static %}



{% block extra_head %}
<title>{{object.title}} - Store | Indian Institute of Drones</title>

<style>
    .prod-detail-div{
        position: relative;
        min-height: 400px;
    }
    .prod-desc2{
        position: absolute;
        bottom: 5px;
        
    }
    @media only screen and (max-device-width: 480px) {
        .card-title{
            font-size: 1.8rem;
        }
    }
</style>

{% endblock %}

{% block content  %}

<div class="container-fluid univ-header">
  <div class="container">
      <div class="row">
          <div class="col-sm-12 text-center">
              <h1>{{object.title}}</h1>
          </div>
      </div>
  </div>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container-fluid">
  <div class="container">
      <div class="row py-3">
          <div class="col-sm-6 text-center my-2">
             <img id="" src="{{object.images.url}}" class="" alt="" width="100%" height="auto">
          </div>
          <div class="col-sm-6 prod-detail-div">
              <h1 class="card-title">{{object.title}}</h4>
              <p class="overflow-auto">{{object.description2|safe}} </p>
              <a class="prod-desc2" href="{{object.add_to_cart}}">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Add to cart <i class="fas fa-cart-plus pl-2"></i></button>
              </a>
          </div>
      </div>
  </div>
</div>

{% endblock %}